# Generated by Django 5.2.7 on 2025-10-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
